package io.github.jamiesanson.broker.util

/**
 * Resolver interface to be generated by compiler
 */
interface RepoResolver {

    /**
     * Function to retrieve the requested class
     */
    fun <T> get(classToFind: Class<T>): T
}